[tool.poetry]
name = "transcription"
version = "0.1.0"
description = ""
authors = ["OscarAcosta17 <oacosta@usm.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
